server:
  port: 8080

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:

#     Isto daqui é para o Keycloack
      default-filters:
        - TokenRelay
#     ====

      discovery:
        locator:
          enabled: true
      routes:
        - id: ONE-SERVICE
          uri:
            lb://ONE-SERVICE

#         Importante que tenha o mesmo nome da classe. Copie e cole para nao errar. Isto eh para JWT
#          filters:
#            - AuthFilter
#        ====
#          Este aqui é para o KeyCloak
          filters:
            - RemoveRequestHeader=Cookie
#        ====

          predicates:
            - Path=/one/**
        - id: TWO-SERVICE
          uri:
            lb://TWO-SERVICE
          predicates:
            - Path=/two/**

        - id: AUTH-SERVICE
          uri:
            lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

# Isto é só para o Keycloack
# https://www.youtube.com/watch?v=uzou3vdmu9Q&list=PL4bT56Uw3S4yTSw5Cg1-mhgoS85fVeFkT&index=12
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/realms/tutorial-realm/protocol/openid-connect/token
        registration:
#          este é o nome que cadastrei no keyloger
          tutorial-client:
            provider: keycloak
            client-id: tutorial-client
            client-secret: IK9JkOMFwbkJNra5tq7X81eI6h7ZAQ4V
            authorization-grant-type: authorization_code
#            o que coloquei la
            redirect-uri: "{baseUrl}/login/oauth2/code/tutorial-client"




eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


