server:
  port: 8080

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ONE-SERVICE
          uri:
            lb://ONE-SERVICE
          filters:
#            Importante que tenha o mesmo nome da classe. Copie e cole para nao errar
            - AuthFilter

          predicates:
            - Path=/one/**
        - id: TWO-SERVICE
          uri:
            lb://TWO-SERVICE
          predicates:
            - Path=/two/**

        - id: AUTH-SERVICE
          uri:
            lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



