version: '3.8'
services:
  gft-keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command:
      [
        'start-dev',

#        nao sei de os comando abaixo sao possiveis mais talvez seja possivel imprtar os dados a baixo

#        'create realms -s realm=Tutorial-realm -s enabled=true -o',

#        'create -s clientId=tutorial-client -s "redirectUris=[\"http://localhost:8080/login/oauth2/code/tutorial-client/*\"]"',
#
#        'create users -s username=user -s enabled=true -r Tutorial-realm'

#        docker exec <CONTAINER> /opt/jboss/keycloak/bin/add-user-keycloak.sh -u <USERNAME> -p <PASSWORD>

      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - DB_VENDOR=h2
      # If you want to expose these ports outside your dev PC,
      # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8180:8080

