version: '3.8'
services:
  gft-mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gft
      - MYSQL_USER=gft
      - MYSQL_ROOT_PASSWORD=gft
      - MYSQL_PASSWORD=gft
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

